### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Spontrel**

### CODE REVIEW

**Comment by Spontrel** [comment]
I hope this method gives you the new code

**Comment by Spontrel** [comment]
I added in a new section to fix the Multiple Delivery Group failure.  It isn't very much code, and you can see it on lines (1036 through 1040) and lines (1172 through 1200).  I updated the file in this pull request

**Comment by ryancbutler** [comment]
@Spontrel  I should have the appgroups and multiple dgs complete in the next day or so.  I have been working on converting it all over to a module vs a giant script.  You can take a look here https://github.com/ryancbutler/XDReplicate/tree/appgroups

**Comment by Spontrel** [comment]
If you mention me in the comments, my name is Scott Pontrelli 

I'm glad I can add to this project.

**Comment by ryancbutler** [comment]
Closing. Thanks for all the help!

**Pull request closed without merging**
